remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Báo cáo Thẩm định Đầu tư - Dự án Nam Phát
description: Báo cáo chi tiết về dự án Nhà Máy sản xuất viên nén năng lượng - gỗ ván ghép thanh
